### ISSUE TITLE
Not compatible with ionic

### ISSUE THREAD

**Issue by kodeine** [MattJeanes/ngx-parallax#10]
So i am trying this with Ionic and the parallax effect does not work even though i passed the `#container` to the config.

`ERROR TypeError: this.scrollElement.addEventListener is not a function`

**Comment by AmyJeanes** [comment]
Hi there, can you please provide an example app I can spin up myself to test? Thanks

**Comment by kodeine** [comment]
@MattJeanes sure you can try this [ionic-conference-app](https://github.com/ionic-team/ionic-conference-app)

**Comment by AmyJeanes** [comment]
Okay, so it looks like this is because ionic handles scrolling a bit weird and creates hidden elements in the page like the `div.scroll-content` element:

![image](https://user-images.githubusercontent.com/2363642/43456916-18c3967e-94bd-11e8-99b6-b1e56f0f6722.png)

It turns out if you pass in specifically the `_scrollContent.nativeElement` property of the <ion-content> element like I have done in my example fork then it will work: https://github.com/MattJeanes/ngx-parallax-ionic-example

Basic example:
```html
<ion-content #scroller class="outer-content">
    <div parallax [config]="{initialValue: -100, ratio: 2, scrollElement: scroller._scrollContent.nativeElement}"></div>
</ion-content>
```

It's not super pretty, but in my testing it seems to work:
![2018-07-31_12-43-25](https://user-images.githubusercontent.com/2363642/43457625-5bef468a-94bf-11e8-9051-1fe46568c007.gif)

Try spinning up the linked test repo and spin that up if you're not sure how it works. Let me know if you got it all working or not!

**Comment by kodeine** [comment]
Thank you :)

**Comment by kodeine** [comment]
Okay I was able to run it fine but i have another issue. The parralex effect apparently starts even if the image is not in viewport. This causes image being in mid way while scrolling. So I see half image already hidden when the image gets into viewport. Any idea what's going on?

**Comment by AmyJeanes** [comment]
Try setting the initialValue in the config to -100 or something. The documentation in the readme should help guide you on how to set offsets etc

**Comment by kodeine** [comment]
If intial value is -100 so the first image on viewport will be -100 as well?

**Comment by AmyJeanes** [comment]
Not 100% sure what you mean but you can configure it per image. Just check out the documentation on the front page of this repo, should explain it better than I can here
